# Site settings
title: Agency Privacy Programs: General Requirements
email: privacy.council@gsa.gov

baseurl: "/slides"
url: "https://slides.18f.gov"

# Build settings
markdown: redcarpet

collections:
  slides:
    output: true
    permalink: "/:path/"
